-- The fields a company can register in, and the Rotabo category each lands
-- in. The list lives in domains.js, which is where it is edited and where the
-- business-side search reads it; this is the same pairs, in the database.
--
-- Why here as well: create-company has to turn a domain into a category, and
-- it carried the pairs as a hard-coded map. That meant every time the list
-- grew -- 113 to 163 to 213 in two days -- the whole function had to be
-- redeployed to add a lookup table, which is a lot of ceremony for a row of
-- data and one more place for the two lists to drift apart.
--
-- Read-only to everyone; only the service role writes. Adding a field is now
-- an insert here and a line in domains.js.

create table if not exists public.domain_categories (
  slug     text primary key,
  category text not null,
  constraint domain_categories_category_check
    check (category in ('drive','translator','move','build','tools','home',
                        'auto','care','learn','stay','pets','other'))
);

alter table public.domain_categories enable row level security;

drop policy if exists "no direct api access" on public.domain_categories;
create policy "no direct api access" on public.domain_categories
  for all to anon, authenticated using (false) with check (false);

insert into public.domain_categories (slug, category) values
  ('taxi','drive'),
  ('ride_hailing','drive'),
  ('chauffeur','drive'),
  ('driving_school','drive'),
  ('translation','translator'),
  ('interpreting','translator'),
  ('sworn_translation','translator'),
  ('language_school','translator'),
  ('removals','move'),
  ('international_removals','move'),
  ('courier','move'),
  ('freight_forwarding','move'),
  ('refrigerated_transport','move'),
  ('haulage','move'),
  ('storage_warehousing','move'),
  ('customs_brokerage','move'),
  ('excavation','build'),
  ('crane_hire','build'),
  ('scaffolding','build'),
  ('demolition','build'),
  ('concrete_works','build'),
  ('surveying','build'),
  ('tool_hire','tools'),
  ('machinery_rental','tools'),
  ('generator_hire','tools'),
  ('electrical_installation','home'),
  ('plumbing','home'),
  ('heating_hvac','home'),
  ('air_conditioning','home'),
  ('painting_decorating','home'),
  ('carpentry','home'),
  ('flooring','home'),
  ('roofing','home'),
  ('locksmith','home'),
  ('cleaning_services','home'),
  ('gardening_landscaping','home'),
  ('renovation','home'),
  ('car_repair','auto'),
  ('mobile_mechanic','auto'),
  ('tyre_service','auto'),
  ('bodywork_paint','auto'),
  ('towing_recovery','auto'),
  ('childcare','care'),
  ('elderly_care','care'),
  ('home_nursing','care'),
  ('private_tutoring','learn'),
  ('music_lessons','learn'),
  ('sports_coaching','learn'),
  ('it_training','learn'),
  ('vocational_training','learn'),
  ('holiday_lettings','stay'),
  ('guesthouse_bnb','stay'),
  ('property_management','stay'),
  ('veterinary','pets'),
  ('dog_walking','pets'),
  ('pet_grooming','pets'),
  ('general_practice','other'),
  ('dentistry','other'),
  ('physiotherapy','other'),
  ('psychology','other'),
  ('pharmacy','other'),
  ('optometry','other'),
  ('medical_laboratory','other'),
  ('software_development','other'),
  ('web_development','other'),
  ('it_support','other'),
  ('cybersecurity','other'),
  ('data_ai','other'),
  ('cloud_hosting','other'),
  ('accounting','other'),
  ('audit_tax','other'),
  ('legal_services','other'),
  ('hr_recruitment','other'),
  ('management_consulting','other'),
  ('insurance_brokerage','other'),
  ('real_estate_agency','other'),
  ('architecture','other'),
  ('manufacturing','other'),
  ('cnc_machining','other'),
  ('metalwork_welding','other'),
  ('restaurant','other'),
  ('catering','other'),
  ('hotel','other'),
  ('event_management','other'),
  ('agriculture','other'),
  ('forestry','other'),
  ('waste_recycling','other'),
  ('renewable_energy','other'),
  ('marketing_agency','other'),
  ('graphic_design','other'),
  ('photography','other'),
  ('video_production','other'),
  ('printing_signage','other'),
  ('wholesale','other'),
  ('ecommerce','other'),
  ('security_services','other'),
  ('shop_general','other'),
  ('shop_bicycle','other'),
  ('shop_auto_parts','auto'),
  ('shop_hardware','tools'),
  ('shop_furniture','home'),
  ('shop_electronics','other'),
  ('shop_clothing','other'),
  ('shop_grocery','other'),
  ('shop_sports','other'),
  ('shop_books','other'),
  ('shop_florist','other'),
  ('shop_pet','pets'),
  ('motorcycle_repair','auto'),
  ('hairdressing','other'),
  ('beauty_salon','other'),
  ('massage_therapy','other'),
  ('fitness_training','other'),
  ('bar','other'),
  ('kebab_shawarma','other'),
  ('pizzeria','other'),
  ('fast_food','other'),
  ('bakery','other'),
  ('pastry_shop','other'),
  ('coffee_shop','other'),
  ('food_truck','other'),
  ('butcher','other'),
  ('ice_cream','other'),
  ('winery','other'),
  ('brewery','other'),
  ('nightclub','other'),
  ('beach_club','stay'),
  ('bowling_billiards','other'),
  ('travel_agency','stay'),
  ('nail_salon','other'),
  ('barber','other'),
  ('tattoo_piercing','other'),
  ('spa_sauna','other'),
  ('cosmetics_shop','other'),
  ('dry_cleaning','other'),
  ('podiatry','other'),
  ('dental_laboratory','other'),
  ('orthodontics','other'),
  ('dermatology','other'),
  ('paediatrics','other'),
  ('gynaecology','other'),
  ('cardiology','other'),
  ('medical_imaging','other'),
  ('speech_therapy','care'),
  ('nutrition_dietetics','other'),
  ('bicycle_repair','other'),
  ('scooter_repair','auto'),
  ('appliance_repair','home'),
  ('phone_repair','other'),
  ('computer_repair','other'),
  ('watch_jewellery_repair','other'),
  ('shoe_repair','other'),
  ('tailoring_alterations','other'),
  ('upholstery','home'),
  ('glazing','build'),
  ('chimney_sweep','home'),
  ('pest_control','home'),
  ('pool_maintenance','home'),
  ('window_cleaning','home'),
  ('car_wash','auto'),
  ('car_rental','drive'),
  ('bike_scooter_rental','drive'),
  ('funeral_services','other'),
  ('notary','other'),
  ('bailiff','other'),
  ('patent_trademark','other'),
  ('debt_collection','other'),
  ('company_formation','other'),
  ('financial_advisory','other'),
  ('payroll_services','other'),
  ('currency_exchange','other'),
  ('pawnshop','other'),
  ('leasing','other'),
  ('hearing_aids','other'),
  ('medical_transport','care'),
  ('rehabilitation','care'),
  ('occupational_therapy','care'),
  ('midwifery','care'),
  ('acupuncture','other'),
  ('chiropractic','other'),
  ('insulation','build'),
  ('waterproofing','build'),
  ('plastering','build'),
  ('tiling','build'),
  ('drywall','build'),
  ('fencing','build'),
  ('paving','build'),
  ('well_drilling','build'),
  ('septic_systems','build'),
  ('solar_panels','home'),
  ('alarm_cctv','home'),
  ('smart_home','home'),
  ('lift_maintenance','build'),
  ('fire_safety','build'),
  ('car_dealer','auto'),
  ('vehicle_inspection','auto'),
  ('auto_electrics','auto'),
  ('car_glass','auto'),
  ('boat_repair','auto'),
  ('bus_charter','drive'),
  ('call_centre','other'),
  ('virtual_assistant','other'),
  ('market_research','other'),
  ('copywriting','other'),
  ('seo_services','other'),
  ('social_media','other'),
  ('app_development','other'),
  ('game_development','other'),
  ('drone_services','other'),
  ('printing_3d','other'),
  ('interior_design','home'),
  ('dance_school','learn'),
  ('art_gallery','other')
on conflict (slug) do update set category = excluded.category;
